/**
 * BpmnConverterDemo
 *
 * Demonstrates the BpmnToFluentConverter by showing the same BPMN process
 * rendered in two ways, stacked vertically:
 *
 *   TOP    — Native XML import (via BpmnDiagram.import / buildDiagram)
 *   BOTTOM — Auto-generated fluent API (via BpmnToFluentConverter.convert)
 */

import { BpmnDiagram } from '../../lib/notations/BpmnDiagram.js';
import { BpmnToFluentConverter } from '../../lib/converters/BpmnToFluentConverter.js';

// Import the BPMN source file as raw XML text
import bpmnXml from '../VueWrapperBpmnDemo/simple-process-template.bpmn?raw';

// ─────────────────────────────────────────────────────────────────────────────
// Helper: create a labelled card wrapper so each diagram has a visible title
// ─────────────────────────────────────────────────────────────────────────────
function createCard(parentContainer, title, subtitle) {
    const card = document.createElement('div');
    card.style.cssText = `
        display: flex;
        flex-direction: column;
        flex: 1 1 0;
        min-height: 0;
        border-bottom: 1px solid #ddd;
        position: relative;
    `;

    // Title bar
    const bar = document.createElement('div');
    bar.style.cssText = `
        padding: 6px 16px;
        background: #f5f5f5;
        border-bottom: 1px solid #e0e0e0;
        display: flex;
        align-items: baseline;
        gap: 12px;
        flex-shrink: 0;
    `;
    const h = document.createElement('span');
    h.textContent = title;
    h.style.cssText = 'font-size: 13px; font-weight: 600; color: #333; font-family: sans-serif;';
    bar.appendChild(h);
    if (subtitle) {
        const s = document.createElement('span');
        s.textContent = subtitle;
        s.style.cssText = 'font-size: 11px; color: #888; font-family: monospace;';
        bar.appendChild(s);
    }
    card.appendChild(bar);

    // Canvas area
    const canvas = document.createElement('div');
    canvas.style.cssText = 'flex: 1 1 0; min-height: 0; position: relative;';
    card.appendChild(canvas);

    parentContainer.appendChild(card);
    return canvas;
}

// ─────────────────────────────────────────────────────────────────────────────
// Main export — called by the demo app loader
// ─────────────────────────────────────────────────────────────────────────────
export default function initDemo(container, options = {}) {

    // Make the host container a vertical flex stack
    container.style.cssText = `
        display: flex;
        flex-direction: column;
        height: 100%;
        overflow: hidden;
    `;

    // ── TOP: Native XML import ────────────────────────────────────────────────
    const topCanvas = createCard(
        container,
        'Native XML Import',
        'BpmnDiagram.buildDiagram(xmlDoc)'
    );

    const nativeDiagram = new BpmnDiagram(topCanvas, options);

    // Parse the XML string into a DOM document and hand it to the diagram
    const parser = new DOMParser();
    const xmlDoc = parser.parseFromString(bpmnXml, 'text/xml');
    nativeDiagram.buildDiagram(xmlDoc);
    nativeDiagram.fitScreen();

    // ── BOTTOM: Fluent API (generated by BpmnToFluentConverter) ───────────────
    const bottomCanvas = createCard(
        container,
        'Auto-generated Fluent API',
        'BpmnToFluentConverter.convert(xml)'
    );

    const fluentDiagram = new BpmnDiagram(bottomCanvas, options);

    // Run the converter
    const converter = new BpmnToFluentConverter();
    const diagram = fluentDiagram; // alias used in eval'd code

    const generatedCode = converter.convert(bpmnXml);

    // Execute the generated code in place — it references `diagram`
    try {
        // eslint-disable-next-line no-new-func
        new Function('diagram', generatedCode)(diagram);
    } catch (err) {
        console.error('[BpmnConverterDemo] Error executing generated code:', err);
        console.log('Generated code that failed:\n' + generatedCode);
    }

    fluentDiagram.arrange();
    fluentDiagram.fitScreen();

    // Return the fluent diagram as the primary instance for the controls panel
    return fluentDiagram;
}
