/**
 * BpmnExporter
 *
 * Exports an Aurea EDEN BpmnDiagram instance to a Camunda-compatible BPMN 2.0 XML string.
 * This class uses a headless BpmnModeler instance to build the XML structure natively,
 * mapping the internal Element and Connector representations back to standard BPMN nodes
 * using the modeling APIs to ensure guaranteed structurally compliant BPMN 2.0 definitions and DIs.
 */
import BpmnModeler from 'bpmn-js/lib/Modeler';

// Import Activity icons for visual-to-semantic matching
import manualIcon from '../../shapes/icon/bpmn/activities/manual.svg?raw';
import userIcon from '../../shapes/icon/bpmn/activities/user.svg?raw';
import scriptIcon from '../../shapes/icon/bpmn/activities/script.svg?raw';
import businessRuleIcon from '../../shapes/icon/bpmn/activities/business-rule.svg?raw';
import serviceIcon from '../../shapes/icon/bpmn/activities/service.svg?raw';
import sendIcon from '../../shapes/icon/bpmn/activities/send.svg?raw';
import receiveIcon from '../../shapes/icon/bpmn/activities/receive.svg?raw';

// Import Event Definitions for visual-to-semantic matching
import messageEndIcon from '../../shapes/icon/bpmn/events/message-end.svg?raw';
import messageStartIcon from '../../shapes/icon/bpmn/events/message-start.svg?raw';
import signalEndIcon from '../../shapes/icon/bpmn/events/signal-end.svg?raw';
import signalStartIcon from '../../shapes/icon/bpmn/events/signal-start.svg?raw';
import terminateIcon from '../../shapes/icon/bpmn/events/terminate.svg?raw';
import timerIcon from '../../shapes/icon/bpmn/events/timer.svg?raw';
import errorIcon from '../../shapes/icon/bpmn/events/error.svg?raw';
import escalationIcon from '../../shapes/icon/bpmn/events/escalation.svg?raw';
import compensationIcon from '../../shapes/icon/bpmn/events/compensation.svg?raw';

export class BpmnExporter {
    /**
     * Exports the given BpmnDiagram to a BPMN 2.0 XML string using bpmn-js.
     * @param {BpmnDiagram} diagram - The diagram to export.
     * @returns {Promise<string>} A promise that resolves to the BPMN XML string.
     */
    async export(diagram) {
        // We use a headless container to avoid DOM attachment side-effects
        const container = document.createElement('div');
        const modeler = new BpmnModeler({ container });

        try {
            await modeler.createDiagram();

            const canvas = modeler.get('canvas');
            const elementFactory = modeler.get('elementFactory');
            const modeling = modeler.get('modeling');
            const elementRegistry = modeler.get('elementRegistry');
            const bpmnFactory = modeler.get('bpmnFactory');

            // Remove default StartEvent generated by createDiagram()
            const defaultStartEvent = elementRegistry.get('StartEvent_1');
            if (defaultStartEvent) {
                modeling.removeElements([defaultStartEvent]);
            }

            const rootElement = canvas.getRootElement();

            // Filter main elements: ignore texts, icons, valueBars, etc.
            const mainElements = diagram.elements.filter(el => {
                if (!el.semanticType || el.semanticType === 'generic') return false;
                if (el.semanticType === 'flow' || el.semanticType === 'swimlane') return false;
                if (el.semanticType === 'anchor') return false;
                if (el.semanticType === 'overlapMarker') return false;
                if (el.isTextElement) return false;
                // Exclude common internally added text/icon components
                if (el.elementId && (el.elementId.endsWith('_text') || el.elementId.includes('_icon_'))) return false;
                return true;
            });

            // Calculate bounding box bounds to shift everything to positive quadrant
            let minX = Infinity;
            let minY = Infinity;

            for (const el of mainElements) {
                const size = el.getSize();
                const halfWidth = Math.abs(size.x) / 2;
                const halfHeight = Math.abs(size.y) / 2;

                // BPMN Y is inverted compared to Aurea (Aurea Y goes up, BPMN Y goes down)
                const left = el.position.x - halfWidth;
                const top = -el.position.y - halfHeight;

                if (left < minX) minX = left;
                if (top < minY) minY = top;
            }

            const offsetX = minX < 0 ? Math.abs(minX) + 100 : Math.max(0, 100 - minX);
            const offsetY = minY < 0 ? Math.abs(minY) + 100 : Math.max(0, 100 - minY);

            const elementIdToShape = {};

            // 1. Create all node elements
            for (const el of mainElements) {
                const bpmnType = this._getBpmnTagName(el);

                const size = el.getSize();
                const width = Math.abs(size.x);
                const height = Math.abs(size.y);

                const shape = elementFactory.createShape({
                    id: el.elementId,
                    type: bpmnType,
                    width: width,
                    height: height
                });

                let labelText = '';
                if (el.texts && el.texts.length > 0) {
                    const validTexts = el.texts.map(t => t.element.textContent).filter(t => t && t.trim().length > 0);
                    if (validTexts.length > 0) {
                        labelText = validTexts[0].replace(/\\n/g, '\n');
                        shape.businessObject.name = labelText;
                    }
                }

                // Center coordinates
                const rawBpmnX = el.position.x + offsetX;
                const rawBpmnY = -el.position.y + offsetY;
                const bpmnX = Math.round(rawBpmnX);
                const bpmnY = Math.round(rawBpmnY);

                const createdShape = modeling.createShape(shape, { x: bpmnX, y: bpmnY }, rootElement);
                elementIdToShape[el.elementId] = createdShape;

                // Add specific event definitions
                let iconSvg = '';
                if (el.icons && el.icons.length > 0 && el.icons[0].element && el.icons[0].element.shape && el.icons[0].element.shape.svgText) {
                    iconSvg = el.icons[0].element.shape.svgText;
                }

                if (createdShape.type === 'bpmn:EndEvent') {
                    if (iconSvg === terminateIcon || (el.elementId && el.elementId.toLowerCase().includes('terminate'))) {
                        const eventDef = bpmnFactory.create('bpmn:TerminateEventDefinition');
                        modeling.updateProperties(createdShape, { eventDefinitions: [eventDef] });
                    } else if (iconSvg === messageEndIcon) {
                        const eventDef = bpmnFactory.create('bpmn:MessageEventDefinition');
                        modeling.updateProperties(createdShape, { eventDefinitions: [eventDef] });
                    } else if (iconSvg === errorIcon) {
                        const eventDef = bpmnFactory.create('bpmn:ErrorEventDefinition');
                        modeling.updateProperties(createdShape, { eventDefinitions: [eventDef] });
                    }
                }
            }

            // 2. Preprocess connections to collapse AnchorPoint chains
            const activeConnectors = [];
            const anchorIn = new Map();
            const anchorOut = new Map();

            for (const connector of diagram.connectors) {
                if (!connector.sourceElement || !connector.targetElement) continue;
                if (connector.sourceElement.semanticType === 'anchor') {
                    anchorOut.set(connector.sourceElement.elementId, connector);
                } else if (connector.targetElement.semanticType === 'anchor') {
                    anchorIn.set(connector.targetElement.elementId, connector);
                } else {
                    activeConnectors.push(connector);
                }
            }

            // Create collapsed connections
            for (const [anchorId, inConn] of anchorIn.entries()) {
                const outConn = anchorOut.get(anchorId);
                if (outConn) {
                    activeConnectors.push({
                        elementId: `${inConn.sourceElement.elementId}_${outConn.targetElement.elementId}_collapsed`,
                        sourceElement: inConn.sourceElement,
                        targetElement: outConn.targetElement,
                        labelElement: inConn.labelElement || outConn.labelElement,
                        isCollapsed: true,
                        anchorElement: outConn.sourceElement // the AnchorPoint element itself
                    });
                }
            }

            // 3. Create connections
            for (const connector of activeConnectors) {
                const sourceShape = elementIdToShape[connector.sourceElement.elementId];
                const targetShape = elementIdToShape[connector.targetElement.elementId];

                if (!sourceShape || !targetShape) continue;

                let connectionAttrs = {
                    id: connector.elementId,
                    type: 'bpmn:SequenceFlow'
                };

                const connection = modeling.createConnection(sourceShape, targetShape, connectionAttrs, rootElement);

                // Add name if label exists
                if (connector.labelElement && connector.labelElement.texts && connector.labelElement.texts.length > 0) {
                    const validTexts = connector.labelElement.texts.map(t => t.element.textContent).filter(t => t && t.trim().length > 0);
                    if (validTexts.length > 0) {
                        modeling.updateProperties(connection, { name: validTexts[0] });
                    }
                }

                // If the real Connector instance has fully routed points, use them directly
                if (connector.points && connector.points.length >= 2) {
                    const newWaypoints = connector.points.map(p => {
                        const rawBpmnX = p.x + offsetX;
                        const rawBpmnY = -p.y + offsetY;

                        const bpmnX = Math.round(rawBpmnX);
                        const bpmnY = Math.round(rawBpmnY);

                        return { x: bpmnX, y: bpmnY };
                    });

                    // Remove identical consecutive points that might have merged due to snapping
                    const filteredWaypoints = [newWaypoints[0]];
                    for (let i = 1; i < newWaypoints.length; i++) {
                        const prev = filteredWaypoints[filteredWaypoints.length - 1];
                        const curr = newWaypoints[i];
                        if (curr.x !== prev.x || curr.y !== prev.y) {
                            filteredWaypoints.push(curr);
                        }
                    }

                    if (filteredWaypoints.length >= 2) {
                        try {
                            modeling.updateWaypoints(connection, filteredWaypoints);
                        } catch (e) {
                            console.warn("Failed to update waypoints for connector " + connector.elementId, e);
                        }
                    }
                }
                // If it's a collapsed connector, we need to add a waypoint for the anchor
                else if (connector.isCollapsed && connector.anchorElement) {
                    const bpmnAnchorX = Math.round(connector.anchorElement.position.x + offsetX);
                    const bpmnAnchorY = Math.round(-connector.anchorElement.position.y + offsetY);

                    const waypoints = connection.waypoints.map(w => ({ original: w, x: w.x, y: w.y }));

                    if (waypoints.length >= 2) {
                        const newWaypoints = [
                            { x: waypoints[0].x, y: waypoints[0].y },
                            { x: bpmnAnchorX, y: bpmnAnchorY },
                            { x: waypoints[waypoints.length - 1].x, y: waypoints[waypoints.length - 1].y }
                        ];
                        try {
                            modeling.updateWaypoints(connection, newWaypoints);
                        } catch (e) {
                            console.warn("Failed to update collapsed waypoints for connector " + connector.elementId, e);
                        }
                    }
                }
            }

            const { xml } = await modeler.saveXML({ format: true });
            modeler.destroy();
            return xml;

        } catch (error) {
            console.error("Failed to export BPMN using bpmn-js:", error);
            modeler.destroy();
            throw error;
        }
    }

    /**
     * Determines precise BPMN tag based on semanticType, properties, or ID convention.
     */
    _getBpmnTagName(el) {
        if (!el) return 'bpmn:Task';

        // 1st Priority: Native Semantic Tagging from BpmnDiagram.js
        if (el.bpmnType) {
            // Note: BpmnModeler requires all End and Start events to be instantiated as the generic
            // bpmn:EndEvent / bpmn:StartEvent, and then the specific EventDefinitions are injected
            // via updateProperties. We normalize them here so the xml structure builds properly.
            if (el.semanticType === 'end-event') return 'bpmn:EndEvent';
            if (el.semanticType === 'start-event') return 'bpmn:StartEvent';

            return el.bpmnType;
        }

        // 2nd Priority: Fallbacks for older elements that missed native tagging
        const type = el.semanticType || 'task';
        const id = el.elementId ? el.elementId.toLowerCase() : '';

        // Safely extract the primary SVG text from the element's icons, if any
        let iconSvg = '';
        if (el.icons && el.icons.length > 0 && el.icons[0].element && el.icons[0].element.shape && el.icons[0].element.shape.svgText) {
            iconSvg = el.icons[0].element.shape.svgText;
        }

        if (type === 'start-event') {
            return 'bpmn:StartEvent';
        }
        if (type === 'end-event') {
            return 'bpmn:EndEvent';
        }
        if (type === 'event') {
            return 'bpmn:IntermediateCatchEvent';
        }
        if (type === 'gateway') {
            if (id.includes('parallel') || id.includes('para')) return 'bpmn:ParallelGateway';
            if (id.includes('inclusive')) return 'bpmn:InclusiveGateway';
            if (id.includes('eventbased') || id.includes('event-based')) return 'bpmn:EventBasedGateway';
            if (id.includes('complex')) return 'bpmn:ComplexGateway';
            return 'bpmn:ExclusiveGateway';
        }
        if (type === 'task') {
            // 1st priority: Explicit icon definition
            if (iconSvg === userIcon) return 'bpmn:UserTask';
            if (iconSvg === serviceIcon) return 'bpmn:ServiceTask';
            if (iconSvg === scriptIcon) return 'bpmn:ScriptTask';
            if (iconSvg === manualIcon) return 'bpmn:ManualTask';
            if (iconSvg === businessRuleIcon) return 'bpmn:BusinessRuleTask';
            if (iconSvg === sendIcon) return 'bpmn:SendTask';
            if (iconSvg === receiveIcon) return 'bpmn:ReceiveTask';

            // 2nd priority: Fallback to ID sniffing for headless tasks without an icon rendering
            if (id.includes('user') || id.includes('approve') || id.includes('human')) return 'bpmn:UserTask';
            if (id.includes('service') || id.includes('system')) return 'bpmn:ServiceTask';
            if (id.includes('script')) return 'bpmn:ScriptTask';
            if (id.includes('manual')) return 'bpmn:ManualTask';
            if (id.includes('business')) return 'bpmn:BusinessRuleTask';
            if (id.includes('send')) return 'bpmn:SendTask';
            if (id.includes('receive')) return 'bpmn:ReceiveTask';

            return 'bpmn:Task';
        }
        return 'bpmn:Task';
    }
}
