export const RoundedRectangleDimensions = {
    ACTIVITY_HORIZONTAL_SIZE: 100,
    ACTIVITY_VERTICAL_SIZE: 80,
    ACTIVITY_CORNER_RADIUS: 10,
    ACTIVITY_LINE_WIDTH: 1,
    ACTIVITY_TEXT_SIZE: 8,
    ACTIVITY_TEXT_ELEVATION: 3
};
    
export const CircleDimensions = {
    EVENT_RADIUS: 18,
    START_EVENT_LINE_WIDTH: 1, 
    END_EVENT_LINE_WIDTH: 2.4, 
    EVENT_TEXT_SIZE: 7,
    EVENT_TEXT_ELEVATION: 3
};

export const DiamondDimensions = {
    GATEWAY_DIAGONAL: 48,
    GATEWAY_LINE_WIDTH: 1,
    GATEWAY_TEXT_SIZE: 7,
    GATEWAY_TEXT_ELEVATION: 3
};
